### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by michaelewens** [kylebarron/jupyterlab-stata-highlight#1]
Hi Kyle:

Thanks for a great extension and the Stata kernel.  I upgrade Jupyter Lab recently (3.0.0) and now cannot reinstall the this extension.  The error is

```
Conflicting Dependencies:
JupyterLab             Extension      Package
>=3.0.0 <3.1.0         >=0.19.1 <0.20.0@jupyterlab/codemirror
```
My codemirror extension is 3.0.0.  Is the best option to force-install the 0.19.1 code mirror?

**Comment by michaelewens** [comment]
Looks like one cannot downgrade to 0.19.1 CodeMirror given the 3.0 Lab install.   Here is my log file from the failed install.  

<details><summary>The log file</summary>
<pre>
Node v14.15.3

Yarn configuration loaded.
> /usr/local/bin/npm pack jupyterlab-stata-highlight
npm notice 
npm notice 📦  jupyterlab-stata-highlight@0.1.1
npm notice === Tarball Contents === 
npm notice 551B   package.json                          
npm notice 1.1kB  LICENSE                               
npm notice 396B   README.md                             
npm notice 674B   Untitled.ipynb                        
npm notice 19.7kB yarn.lock                             
npm notice 275B   jupyterlab-stata-highlight/__init__.py
npm notice 474B   lib/plugin.js                         
npm notice 28.0kB lib/stata.js                          
npm notice === Tarball Details === 
npm notice name:          jupyterlab-stata-highlight              
npm notice version:       0.1.1                                   
npm notice filename:      jupyterlab-stata-highlight-0.1.1.tgz    
npm notice package size:  16.7 kB                                 
npm notice unpacked size: 51.1 kB                                 
npm notice shasum:        dbcd8df1e9fb9119ad44c5d4a27be28d0d6d6f9a
npm notice integrity:     sha512-SW6yspwUGTfvM[...]/1hh5q45LRRPA==
npm notice total files:   8                                       
npm notice 
jupyterlab-stata-highlight-0.1.1.tgz

Fetching URL: https://registry.yarnpkg.com/jupyterlab-stata-highlight
Fetching URL: https://registry.yarnpkg.com/jupyterlab-stata-highlight
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 127, in start
    ans = self.run_task()

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 178, in run_task
    for i, arg in enumerate(self.extra_args)

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 178, in <listcomp>
    for i, arg in enumerate(self.extra_args)

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 392, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 614, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1677, in _install_extension
    raise ValueError(msg)

ValueError: The extension "jupyterlab-stata-highlight" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab             Extension      Package
>=3.0.0 <3.1.0         >=0.19.1 <0.20.0@jupyterlab/codemirror

Exiting application: lab
</pre>
</details>

**Comment by kylebarron** [comment]
If you figure out the issue you're welcome to submit a Pull Request

**Comment by michaelewens** [comment]
I tried the development install option:
* download repo
* replace line 22 of `package.json` with 3.0.0
* run `npm install` followed by `jupyter labextension link .` in the local repo directory. 
Now it works.   I am better at uploading repos to Gitbub than doing pull requests, but let me try.
